spark.eventLog.enabled true
spark.eventLog.dir hdfs://rancluster/spark-logs
spark.serializer org.apache.spark.serializer.KryoSerializer
spark.driver.memory 1g
spark.executor.memory 1g
spark.sql.shuffle.partitions 200
